name: Build adocs and deploy skos-ap-no to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - skos-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy skos-ap-no-begrep to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: skos-ap-no
      destination_dir: ./skos-ap-no
      keep_files: true
      program: "asciidoctor -D skos-ap-no -o index.html -a lang=en skos-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
