name: Build adocs and deploy dcat-ap-no to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - dcat-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy dcat-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: dcat-ap-no
      destination_dir: ./dcat-ap-no
      keep_files: true
      program: "asciidoctor -D dcat-ap-no -o index.html -a lang=en dcat-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
