name: Build adocs and deploy cpsv-ap-no to data.norge.no

on:
  push:
    branches:
      - main
    paths:
      - cpsv-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build_cpsv:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: adoc build cpsv
    with:
      host: 'https://data.norge.no'
      ontology: 'cpsv-ap-no'
      ontology-type: 'showroom'
      program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"
      files: |
        cpsv-ap-no/index.html text/html en
        cpsv-ap-no/files/demo-services-events.ttl text/turtle en
        cpsv-ap-no/files/demo-services-events-en.html text/html en
        cpsv-ap-no/files/demo-services-events-nb.html text/html nb
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
