name: Build cpsv adocs and deploy to data.norge.no

permissions:
  contents: read

on:
   push:
     branches:
       - main-test
     paths:
       - cpsv-ap-no/**

jobs:
   adoc_build:
      runs-on: ubuntu-latest
      name: asciidoctor build
  
      steps:
        - name: Checkout code
          uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
          with:
            ref: main

        - name: cpsv-root-files-en
          id: adocbuild-cpsv-root-files-en
          uses: Analog-inc/asciidoctor-action@master
          with:
            shellcommand: "asciidoctor -D cpsv-ap-no -o index-en.html -a lang=en cpsv-ap-no/main-en.adoc"

        - name: cpsv-root-files-nb
          id: adocbuild-cpsv-root-files-nb
          uses: Analog-inc/asciidoctor-action@master
          with:
            shellcommand: "asciidoctor -D cpsv-ap-no -o index-nb.html -a lang=nb cpsv-ap-no/main-nb.adoc"
            
        - name: cpsv-demo-files-en
          id: adocbuild-cpsv-demo-files-en
          uses: Analog-inc/asciidoctor-action@master
          with:
            shellcommand: "asciidoctor -D cpsv-ap-no/files -o demo-services-events-en.html -a lang=en cpsv-ap-no/files/main-en.adoc"

        - name: cpsv-demo-files-nb
          id: adocbuild-cpsv-demo-files-files-nb
          uses: Analog-inc/asciidoctor-action@master
          with:
             shellcommand: "asciidoctor -D cpsv-ap-no/files -o demo-services-events-nb.html -a lang=nb cpsv-ap-no/files/main-nb.adoc"

        - name: Upload cpsv-files to static-rdf-server
          uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@f9b41f11e07006762215dbd80a6e09b97834f93c
          id: upload-cpsv-files
          with:
            ontology-type: "showroom"
            ontology: "cpsv-ap-no"
            host: "https://data.norge.no"
            api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
            files: |   
              cpsv-ap-no/index-en.html text/html en
              cpsv-ap-no/index-nb.html text/html nb
              cpsv-ap-no/images/Digdir.png image/png en images/Digdir.png
              cpsv-ap-no/images/demoPublicService1-explanation.png image/png en images/demoPublicService1-explanation.png
              cpsv-ap-no/files/demo-services-events.ttl text/turtle en demo-services-events/demo-services-events.ttl
              cpsv-ap-no/files/demo-services-events-en.html text/html en demo-services-events/demo-services-events-en.html
              cpsv-ap-no/files/demo-services-events-nb.html text/html nb demo-services-events/demo-services-events-nb.html
