name: Build adocs and deploy specification to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - cpsv-ap-no/**
      - dcat-ap-no/**
      - docs/**
      - demo-uris/**
      - dummy-assets/**
      - modelldcat-ap-no/**
      - skos-ap-no/**
      - xkos-ap-no/**
  workflow_dispatch:

jobs:
  filter_path:
    name: Setup path filter
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      cpsv: ${{ steps.filter.outputs.cpsv }}
      dcat: ${{ steps.filter.outputs.dcat }}
      docs: ${{ steps.filter.outputs.docs }}
      demo_uris: ${{ steps.filter.outputs.demo_uris }}
      dummy_assets: ${{ steps.filter.outputs.dummy_assets }}
      modelldcat: ${{ steps.filter.outputs.modelldcat }}
      skos: ${{ steps.filter.outputs.skos }}
      xkos: ${{ steps.filter.outputs.xkos }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Filter
      uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          cpsv:
            - 'cpsv-ap-no/**'
          dcat:
            - 'dcat-ap-no/**'
          docs:
            - 'docs/**'
          demo_uris:
            - 'demo-uris/**'
          dummy_assets:
            - 'dummy-assets/**'
          modelldcat:
            - 'modelldcat-ap-no/**'
          skos:
            - 'skos-ap-no/**'
          xkos:
            - 'xkos-ap-no/**'

  cpsv_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.cpsv == 'true' }}
    name: Deploy cpsv-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: cpsv-ap-no
      destination_dir: ./cpsv-ap-no
      keep_files: true
      program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dcat_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.dcat == 'true' }}
    name: Deploy dcat-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: dcat-ap-no
      destination_dir: ./dcat-ap-no
      keep_files: true
      program: "asciidoctor -D dcat-ap-no -o index.html -a lang=en dcat-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  demo_uris_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.demo_uris == 'true' }}
    name: Deploy demo-uris to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: demo-uris
      destination_dir: ./demo-uris
      keep_files: true
      program: "asciidoctor -D demo-uris -o index.html -a lang=en demo-uris/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dummy_assets_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.dummy_assets == 'true' }}
    name: Deploy dummy-assets to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: dummy-assets
      destination_dir: ./dummy-assets
      keep_files: true
      program: "asciidoctor -D dummy-assets -o index.html -a lang=en dummy-assets/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  modelldcat_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.modelldcat == 'true' }}
    name: Deploy modelldcat-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: modelldcat-ap-no
      destination_dir: ./modelldcat-ap-no
      keep_files: true
      program: "asciidoctor -D modelldcat-ap-no -o index.html -a lang=en modelldcat-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  root_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.root == 'true' }}
    name: Deploy root to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: ./docs
      destination_dir: ./overview
      keep_files: true
      program: "asciidoctor -D docs -o index.html -a lang=en docs/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  skos_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.skos == 'true' }}
    name: Deploy skos-ap-no-begrep to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: skos-ap-no
      destination_dir: ./skos-ap-no
      keep_files: true
      program: "asciidoctor -D skos-ap-no -o index.html -a lang=en skos-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  xkos_build_deploy:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    if: ${{ needs.filter_path.outputs.xkos == 'true' }}
    name: Deploy xkos-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: xkos-ap-no
      destination_dir: ./xkos-ap-no
      keep_files: true
      program: "asciidoctor -D xkos-ap-no -o index.html -a lang=en xkos-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
