name: Build adocs and deploy dummy-assets to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - dummy-assets/**
  workflow_dispatch:

jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy dummy-assets to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: dummy-assets
      destination_dir: ./dummy-assets
      keep_files: true
      program: "asciidoctor -D dummy-assets -o index.html -a lang=en dummy-assets/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
