name: Build adocs and deploy demo-uris to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - demo-uris/**
  workflow_dispatch:

jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy demo-uris to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: demo-uris
      destination_dir: ./demo-uris
      keep_files: true
      program: "asciidoctor -D demo-uris -o index.html -a lang=en demo-uris/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
