name: Build adocs and deploy root to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - docs/**
  workflow_dispatch:
jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy root to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: ./docs
      keep_files: true
      program: "asciidoctor -D docs -o index.html -a lang=en docs/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
