name: Build adocs and deploy specification to data.norge.no

on:
  push:
    branches:
      - main
    paths:
      - cpsv-ap-no/**
      - docs/**
  workflow_dispatch:

jobs:
  filter_path:
    name: Setup path filter
    runs-on: ubuntu-latest
    steps:
    - name: Filter
      uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          cpsv:
            - 'cpsv-ap-no/**'
          root:
            - 'docs/**'

  adoc_build_upload_cpsv:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    if: ${{ filter_path.changes.outputs.cpsv == 'true' }}
    name: Build and upload cpsv
    with:
      host: 'https://data.norge.no'
      ontology: 'cpsv-ap-no'
      ontology-type: 'showroom'
      program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"
      files: |
        cpsv-ap-no/index.html text/html en
        cpsv-ap-no/files/demo-services-events.ttl text/turtle en
        cpsv-ap-no/files/demo-services-events-en.html text/html en
        cpsv-ap-no/files/demo-services-events-nb.html text/html nb
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

  adoc_build_upload_root:
    needs: filter_path
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    if: ${{ filter_path.changes.outputs.root == 'true' }}
    name: Build and upload root
    with:
      ontology-type: "showroom"
      ontology: ""
      host: "https://data.norge.no"
      program: "asciidoctor -D docs -o index.html -a lang=en docs/main.adoc"
      files: |
        docs/index.html text/html en
        docs/images/crossreferencing-between-showrooms.png image/png en images/crossreferencing-between-showrooms.png
        docs/images/Digdir.png image/png en images/Digdir.png
        docs/images/registering-n-harvesting.png image/png en images/registering-n-harvesting.png
        docs/images/work-in-progress.png image/png en images/work-in-progress.png
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
