name: Build adocs and deploy cpsv-ap-no to Github Pages

on:
  push:
    branches:
      - develop
    paths:
      - cpsv-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    name: deploy cpsv-ap-no to GitHub Pages
    with:
      publish_branch: gh-pages
      publish_dir: cpsv-ap-no
      destination_dir: ./cpsv-ap-no
      keep_files: true
      program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
