name: Build adocs and deploy cpsv-ap-no to data.norge.no

on:
  push:
    branches:
      - main
    paths:
      - cpsv-ap-no/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build html
        id: adocbuild_html
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"

      - name: Upload to data.norge.no
        uses: informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          ontology-type: "showroom"
          ontology: "cpsv-ap-no"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            cpsv-ap-no/index.html text/html en
            cpsv-ap-no/files/demo-services-events.ttl text/turtle en
            cpsv-ap-no/files/ddemo-services-events-en.html text/html en
            cpsv-ap-no/files/ddemo-services-events-nb.html text/html nb