name: Build adocs and deploy root to data.norge.no

on:
  push:
    branches:
      - main
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build_root:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: adoc build root
    with:
      ontology-type: "showroom"
      ontology: ""
      host: "https://data.norge.no"
      program: "asciidoctor -D docs -o index.html -a lang=en docs/main.adoc"
      files: |
        docs/index.html text/html en
        docs/images/crossreferencing-between-showrooms.png image/png en images/crossreferencing-between-showrooms.png
        docs/images/Digdir.png image/png en images/Digdir.png
        docs/images/registering-n-harvesting.png image/png en images/registering-n-harvesting.png
        docs/images/work-in-progress.png image/png en images/work-in-progress.png
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
