name: Manually build adocs and deploy showroom to data.norge.no

on:
  workflow_dispatch:

jobs:
  cpsv_build_upload:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: cpsv
    with:
      host: "https://data.norge.no"
      ontology: "cpsv-ap-no"
      ontology-type: "showroom"
      program: "asciidoctor -D cpsv-ap-no -o index.html -a lang=en cpsv-ap-no/main.adoc"
      files: |
        cpsv-ap-no/index.html text/html en
        cpsv-ap-no/images/Digdir.png image/png en images/Digdir.png
        cpsv-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        cpsv-ap-no/files/demo-services-events.ttl text/turtle en files/demo-services-events.ttl
        cpsv-ap-no/files/demo-services-events-en.html text/html en files/demo-services-events-en.html
        cpsv-ap-no/files/demo-services-events-nb.html text/html nb files/demo-services-events-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

  dcat_build_upload:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: dcat
    with:
      host: "https://data.norge.no"
      ontology: "dcat-ap-no"
      ontology-type: "showroom"
      program: "asciidoctor -D dcat-ap-no -o index.html -a lang=en dcat-ap-no/main.adoc"
      files: |
        dcat-ap-no/index.html text/html en
        dcat-ap-no/images/Digdir.png image/png en images/Digdir.png
        dcat-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        dcat-ap-no/files/demo-datasets.ttl text/turtle en files/demo-datasets.ttl
        dcat-ap-no/files/demo-datasets-en.html text/html en files/demo-datasets-en.html
        dcat-ap-no/files/demo-datasets-nb.html text/html nb files/demo-datasets-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

  demo_uris_build_upload:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: demo-uris
    with:
      host: "https://data.norge.no"
      ontology: "demo-uris"
      ontology-type: "showroom"
      program: "asciidoctor -D demo-uris -o index.html -a lang=en demo-uris/main.adoc"
      files: |
        demo-uris/index.html text/html en
        demo-uris/images/Digdir.png image/png en images/Digdir.png
        demo-uris/images/work-in-progress.png image/png en images/work-in-progress.png
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

  dummy_assets_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: dummy-assets
    with:
      host: "https://data.norge.no"
      ontology: "dummy-assets"
      ontology-type: "showroom"
      program: "asciidoctor -D dummy-assets -o index.html -a lang=en dummy-assets/main.adoc"
      files: |
        dummy-assets/index.html text/html en
        dummy-assets/images/Digdir.png image/png en images/Digdir.png
        dummy-assets/images/work-in-progress.png image/png en images/work-in-progress.png
        dummy-assets/files/dummy-agents.ttl text/turtle en dummy-agents/dummy-agents.ttl
        dummy-assets/files/dummy-agents-en.html text/html en dummy-agents/dummy-agents-en.html
        dummy-assets/files/dummy-agents-nb.html text/html nb dummy-agents/dummy-agents-nb.html
        dummy-assets/files/dummy-contact-points.ttl text/turtle en dummy-contact-points/dummy-contact-points.ttl
        dummy-assets/files/dummy-contact-points-en.html text/html en dummy-contact-points/dummy-contact-points-en.html
        dummy-assets/files/dummy-contact-points-nb.html text/html nb dummy-contact-points/dummy-contact-points-nb.html
        dummy-assets/files/dummy-datasets.ttl text/turtle en dummy-datasets/dummy-datasets.ttl
        dummy-assets/files/dummy-datasets-en.html text/html en dummy-datasets/dummy-datasets-en.html
        dummy-assets/files/dummy-datasets-nb.html text/html nb dummy-datasets/dummy-datasets-nb.html
        dummy-assets/files/dummy-documents.ttl text/turtle en dummy-documents/dummy-documents.ttl
        dummy-assets/files/dummy-documents-en.html text/html en dummy-documents/dummy-documents-en.html
        dummy-assets/files/dummy-documents-nb.html text/html nb dummy-documents/dummy-documents-nb.html
        dummy-assets/files/dummy-events.ttl text/turtle en dummy-events/dummy-events.ttl
        dummy-assets/files/dummy-events-en.html text/html en dummy-events/dummy-events-en.html
        dummy-assets/files/dummy-events-nb.html text/html nb dummy-events/dummy-events-nb.html
        dummy-assets/files/dummy-evidences.ttl text/turtle en dummy-evidences/dummy-evidences.ttl
        dummy-assets/files/dummy-evidences-en.html text/html en dummy-evidences/dummy-evidences-en.html
        dummy-assets/files/dummy-evidences-nb.html text/html nb dummy-evidences/dummy-evidences-nb.html
        dummy-assets/files/dummy-locations.ttl text/turtle en dummy-locations/dummy-locations.ttl
        dummy-assets/files/dummy-locations-en.html text/html en dummy-locations/dummy-locations-en.html
        dummy-assets/files/dummy-locations-nb.html text/html nb dummy-locations/dummy-locations-nb.html
        dummy-assets/files/dummy-services.ttl text/turtle en dummy-services/dummy-services.ttl
        dummy-assets/files/dummy-services-en.html text/html en dummy-services/dummy-services-en.html
        dummy-assets/files/dummy-services-nb.html text/html nb dummy-services/dummy-services-nb.html
        dummy-assets/files/dummy-times.ttl text/turtle en dummy-times/dummy-times.ttl
        dummy-assets/files/dummy-times-en.html text/html en dummy-times/dummy-times-en.html
        dummy-assets/files/dummy-times-nb.html text/html nb dummy-times/dummy-times-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
  
  modelldcat_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: modelldcat
    with:
      host: "https://data.norge.no"
      ontology: "modelldcat-ap-no"
      ontology-type: "showroom"
      program: "asciidoctor -D modelldcat-ap-no -o index.html -a lang=en modelldcat-ap-no/main.adoc"
      files: |
        modelldcat-ap-no/index.html text/html en
        modelldcat-ap-no/files/demo-models.ttl text/turtle en files/demo-models.ttl
        modelldcat-ap-no/files/demo-models-en.html text/html en files/demo-models-en.html
        modelldcat-ap-no/files/demo-models-nb.html text/html nb files/demo-models-nb.html
        modelldcat-ap-no/images/Digdir.png image/png en images/Digdir.png
        modelldcat-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        modelldcat-ap-no/images/demomodel1.png image/png en images/demomodel1.png
        modelldcat-ap-no/images/demomodel1-mapping-examples.png image/png en images/demomodel1-mapping-examples.png
        modelldcat-ap-no/images/demomodel2.png image/png en images/demomodel2.png
        modelldcat-ap-no/images/demomodel3.png image/png en images/demomodel3.png
        modelldcat-ap-no/images/demomodel4.png image/png en images/demomodel4.png
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
   
  overview_build_upload:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: overview
    with:
      ontology-type: "showroom"
      ontology: "overview"
      host: "https://data.norge.no"
      program: "asciidoctor -D overview -o index.html -a lang=en overview/main.adoc"
      files: |
        overview/index.html text/html en
        overview/images/crossreferencing-between-showrooms.png image/png en images/crossreferencing-between-showrooms.png
        overview/images/Digdir.png image/png en images/Digdir.png
        overview/images/registering-n-harvesting.png image/png en images/registering-n-harvesting.png
        overview/images/work-in-progress.png image/png en images/work-in-progress.png
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

  skos_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: skos-ap-no-begrep
    with:
      ontology-type: "showroom"
      ontology: "skos-ap-no"
      host: "https://data.norge.no"
      program: "asciidoctor -D skos-ap-no -o index.html -a lang=en skos-ap-no/main.adoc"
      files: |
        skos-ap-no/index.html text/html en
        skos-ap-no/images/Digdir.png image/png en images/Digdir.png
        skos-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        skos-ap-no/images/concept-diagrams-iso.png image/png en images/concept-diagrams-iso.png
        skos-ap-no/images/concept-models-uml.png image/png en images/concept-models-uml.png
        skos-ap-no/images/hierarchical-relations-explanations.png image/png en images/hierarchical-relations-explanations.png
        skos-ap-no/files/demo-concepts.ttl text/turtle en files/demo-concepts.ttl
        skos-ap-no/files/demo-concepts-en.html text/html en files/demo-concepts-en.html
        skos-ap-no/files/demo-concepts-nb.html text/html nb files/demo-concepts-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
 
  xkos_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: xkos-ap-no
    with:
      ontology-type: "showroom"
      ontology: "xkos-ap-no"
      host: "https://data.norge.no"
      program: "asciidoctor -D xkos-ap-no -o index.html -a lang=en xkos-ap-no/main.adoc"
      files: |
        xkos-ap-no/index.html text/html en
        xkos-ap-no/images/Digdir.png image/png en images/Digdir.png
        xkos-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        xkos-ap-no/images/demo-classification1.png image/png en images/demo-classification1.png
        xkos-ap-no/files/demo-classifications.ttl text/turtle en files/demo-classifications.ttl
        xkos-ap-no/files/demo-classifications-en.html text/html en files/demo-classifications-en.html
        xkos-ap-no/files/demo-classifications-nb.html text/html nb files/demo-classifications-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
    