name: Manually deploy showroom-root to data.norge.no/showroom

on:
   push:
      branches:
        - main
      paths:
        - index.html
   workflow_dispatch:
  
jobs:
 
   root_upload:
      name: Upload root index to data.norge.no/showroom
      runs-on: ubuntu-latest
      if: github.event.pull_request.draft == false

      steps: 
      -  name: Checkout code
         uses: actions/checkout@v3
 
      -  name: root-upload
         uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
         id: upload-root
         with:
            ontology-type: "showroom"
            ontology: "./"
            host: "https://data.norge.no"
            api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
            files: |
               index.html text/html en

    