name: Test Manually upload dummy-assets-files to data.norge.no/showroom

on:
  workflow_dispatch:

jobs:
  dummy_assets_build_deploy:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: dummy-assets
    with:
      host: "https://data.norge.no"
      ontology: "dummy-assets"
      ontology-type: "showroom"
      program: "asciidoctor -D dummy-assets -o index.html -a lang=en dummy-assets/main.adoc"
      files: |
        dummy-assets/index.html text/html en
        dummy-assets/images/Digdir.png image/png en images/Digdir.png
        dummy-assets/images/work-in-progress.png image/png en images/work-in-progress.png
        dummy-assets/files/dummy-agents.ttl text/turtle en dummy-agents/dummy-agents.ttl
        dummy-assets/files/dummy-agents-en.html text/html en dummy-agents/dummy-agents-en.html
        dummy-assets/files/dummy-agents-nb.html text/html nb dummy-agents/dummy-agents-nb.html
        dummy-assets/files/dummy-contact-points.ttl text/turtle en dummy-contact-points/dummy-contact-points.ttl
        dummy-assets/files/dummy-contact-points-en.html text/html en dummy-contact-points/dummy-contact-points-en.html
        dummy-assets/files/dummy-contact-points-nb.html text/html nb dummy-contact-points/dummy-contact-points-nb.html
        dummy-assets/files/dummy-datasets.ttl text/turtle en dummy-datasets/dummy-datasets.ttl
        dummy-assets/files/dummy-datasets-en.html text/html en dummy-datasets/dummy-datasets-en.html
        dummy-assets/files/dummy-datasets-nb.html text/html nb dummy-datasets/dummy-datasets-nb.html
        dummy-assets/files/dummy-documents.ttl text/turtle en dummy-documents/dummy-documents.ttl
        dummy-assets/files/dummy-documents-en.html text/html en dummy-documents/dummy-documents-en.html
        dummy-assets/files/dummy-documents-nb.html text/html nb dummy-documents/dummy-documents-nb.html
        dummy-assets/files/dummy-events.ttl text/turtle en dummy-events/dummy-events.ttl
        dummy-assets/files/dummy-events-en.html text/html en dummy-events/dummy-events-en.html
        dummy-assets/files/dummy-events-nb.html text/html nb dummy-events/dummy-events-nb.html
        dummy-assets/files/dummy-evidences.ttl text/turtle en dummy-evidences/dummy-evidences.ttl
        dummy-assets/files/dummy-evidences-en.html text/html en dummy-evidences/dummy-evidences-en.html
        dummy-assets/files/dummy-evidences-nb.html text/html nb dummy-evidences/dummy-evidences-nb.html
        dummy-assets/files/dummy-locations.ttl text/turtle en dummy-locations/dummy-locations.ttl
        dummy-assets/files/dummy-locations-en.html text/html en dummy-locations/dummy-locations-en.html
        dummy-assets/files/dummy-locations-nb.html text/html nb dummy-locations/dummy-locations-nb.html
        dummy-assets/files/dummy-services.ttl text/turtle en dummy-services/dummy-services.ttl
        dummy-assets/files/dummy-services-en.html text/html en dummy-services/dummy-services-en.html
        dummy-assets/files/dummy-services-nb.html text/html nb dummy-services/dummy-services-nb.html
        dummy-assets/files/dummy-times.ttl text/turtle en dummy-times/dummy-times.ttl
        dummy-assets/files/dummy-times-en.html text/html en dummy-times/dummy-times-en.html
        dummy-assets/files/dummy-times-nb.html text/html nb dummy-times/dummy-times-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
   