name: Test manually upload to data.norge.no/showroom

on:
  workflow_dispatch:

jobs:
  cpsv_build_upload:
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    name: cpsv
    with:
      host: "https://data.norge.no"
      ontology: "cpsv-ap-no"
      ontology-type: "showroom"
      program: "asciidoctor -D cpsv-ap-no -o index-en.html -a lang=en cpsv-ap-no/main.adoc"
      files: |
        cpsv-ap-no/index-en.html text/html en index-en.html
        cpsv-ap-no/index-nb.html text/html nb index-nb.html
        cpsv-ap-no/images/Digdir.png image/png en images/Digdir.png
        cpsv-ap-no/images/work-in-progress.png image/png en images/work-in-progress.png
        cpsv-ap-no/files/demo-services-events.ttl text/turtle en demo-services-events/demo-services-events.ttl
        cpsv-ap-no/files/demo-services-events-en.html text/html en demo-services-events/demo-services-events-en.html
        cpsv-ap-no/files/demo-services-events-nb.html text/html nb demo-services-events/demo-services-events-nb.html
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}

